# Generated by Django 3.1.4 on 2020-12-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
